export const NATIONALITIES = [
  'Afghan','Albanian','Algerian','American','Andorran','Angolan','Argentine','Armenian',
  'Australian','Austrian','Azerbaijani','Bahamian','Bahraini','Bangladeshi','Barbadian',
  'Belarusian','Belgian','Belizean','Beninese','Bhutanese','Bolivian','Bosnian','Botswanan',
  'Brazilian','British','Bruneian','Bulgarian','Burkinabe','Burmese','Burundian','Cambodian',
  'Cameroonian','Canadian','Cape Verdean','Central African','Chadian','Chilean','Chinese',
  'Colombian','Comorian','Congolese','Costa Rican','Croatian','Cuban','Cypriot','Czech',
  'Danish','Djiboutian','Dominican','Dutch','East Timorese','Ecuadorean','Egyptian',
  'Emirati','Equatorial Guinean','Eritrean','Estonian','Ethiopian','Fijian','Finnish',
  'French','Gabonese','Gambian','Georgian','German','Ghanaian','Greek','Grenadian',
  'Guatemalan','Guinean','Guyanese','Haitian','Honduran','Hungarian','Icelandic','Indian',
  'Indonesian','Iranian','Iraqi','Irish','Israeli','Italian','Ivorian','Jamaican','Japanese',
  'Jordanian','Kazakhstani','Kenyan','Korean','Kosovar','Kuwaiti','Kyrgyz','Laotian',
  'Latvian','Lebanese','Liberian','Libyan','Liechtenstein','Lithuanian','Luxembourgish',
  'Macedonian','Malagasy','Malawian','Malaysian','Maldivian','Malian','Maltese','Mauritanian',
  'Mauritian','Mexican','Moldovan','Monacan','Mongolian','Montenegrin','Moroccan',
  'Mozambican','Namibian','Nepalese','New Zealander','Nicaraguan','Nigerian','Nigerien',
  'Norwegian','Omani','Pakistani','Palauan','Panamanian','Papua New Guinean','Paraguayan',
  'Peruvian','Filipino','Polish','Portuguese','Qatari','Romanian','Russian','Rwandan',
  'Saint Lucian','Salvadoran','Samoan','Saudi','Senegalese','Serbian','Sierra Leonean',
  'Singaporean','Slovak','Slovenian','Somali','South African','South Sudanese','Spanish',
  'Sri Lankan','Sudanese','Surinamese','Swazi','Swedish','Swiss','Syrian','Taiwanese',
  'Tajik','Tanzanian','Thai','Togolese','Trinidadian','Tunisian','Turkish','Turkmen',
  'Ugandan','Ukrainian','Uruguayan','Uzbek','Venezuelan','Vietnamese','Yemeni','Zambian',
  'Zimbabwean',
]
