import crypto from 'crypto'
import type { NextRequest } from 'next/server'
import type { getDb } from '@/lib/get-db'

type Db = Awaited<ReturnType<typeof getDb>>

// Same lifetime the manual "Get Receive Link" flow has always used.
const TOKEN_TTL_MS = 14 * 24 * 60 * 60 * 1000

/** Base URL for a no-login receive link, resolved the same way whether the token was
 * generated by a manual "Get Receive Link" click or auto-sent on dispatch. */
export function resolveBaseUrl(req: NextRequest): string {
  const fwdProto = req.headers.get('x-forwarded-proto')?.split(',')[0]?.trim()
  const fwdHost = req.headers.get('x-forwarded-host')?.split(',')[0]?.trim()
  return fwdProto && fwdHost
    ? `${fwdProto}://${fwdHost}`
    : (process.env.NEXTAUTH_URL ?? `${req.nextUrl.protocol}//${req.nextUrl.host}`)
}

/** Reuses a still-valid PurchaseOrder.receiveToken, or mints a new one. Shared by the
 * manual receive-link button (src/app/api/purchasing/orders/[id]/receive-link/route.ts)
 * and the automatic notification sent to a yacht's assigned Boat Captain/Cruise Director
 * when the PO goes IN_TRANSIT. */
export async function getOrCreatePoReceiveToken(db: Db, poId: string): Promise<{ token: string; expiresAt: Date }> {
  const order = await db.purchaseOrder.findUniqueOrThrow({ where: { id: poId }, select: { receiveToken: true, receiveTokenExpiresAt: true } })
  const stillValid = order.receiveToken && order.receiveTokenExpiresAt && new Date(order.receiveTokenExpiresAt) > new Date()
  if (stillValid) return { token: order.receiveToken!, expiresAt: order.receiveTokenExpiresAt! }

  const token = crypto.randomBytes(32).toString('hex')
  const expiresAt = new Date(Date.now() + TOKEN_TTL_MS)
  await db.purchaseOrder.update({ where: { id: poId }, data: { receiveToken: token, receiveTokenExpiresAt: expiresAt } })
  return { token, expiresAt }
}

/** Same as getOrCreatePoReceiveToken, for StockTransfer (mirrors
 * src/app/api/purchasing/transfers/[id]/receive-link/route.ts). */
export async function getOrCreateTransferReceiveToken(db: Db, transferId: string): Promise<{ token: string; expiresAt: Date }> {
  const transfer = await db.stockTransfer.findUniqueOrThrow({ where: { id: transferId }, select: { receiveToken: true, receiveTokenExpiresAt: true } })
  const stillValid = transfer.receiveToken && transfer.receiveTokenExpiresAt && new Date(transfer.receiveTokenExpiresAt) > new Date()
  if (stillValid) return { token: transfer.receiveToken!, expiresAt: transfer.receiveTokenExpiresAt! }

  const token = crypto.randomBytes(32).toString('hex')
  const expiresAt = new Date(Date.now() + TOKEN_TTL_MS)
  await db.stockTransfer.update({ where: { id: transferId }, data: { receiveToken: token, receiveTokenExpiresAt: expiresAt } })
  return { token, expiresAt }
}
