'use client'

// Shared Add/Edit Item form body — used by Items & Pricing and by Stock Opname Awal's
// Add/Edit Product popups so both show the exact same product form. Only the fields;
// each caller owns its modal shell, save call and any extra fields (e.g. opname qty).

import type { Dispatch, SetStateAction } from 'react'
import { ToggleLeft, ToggleRight, Upload, Package, UtensilsCrossed, Wine, Wrench, Boxes, Waves, SprayCan, type LucideIcon } from 'lucide-react'
import { useFileDrop } from '@/hooks/useFileDrop'

const ITEM_TYPE_ICON: Record<string, LucideIcon> = {
  FOOD: UtensilsCrossed,
  BEVERAGE: Wine,
  MAINTENANCE: Wrench,
  MATERIAL: Boxes,
  DIVING: Waves,
  HOUSEKEEPING: SprayCan,
}
export function getTypeIcon(code: string): LucideIcon {
  return ITEM_TYPE_ICON[code] ?? Package
}

export interface ItemCategory { name: string; skuPrefix: string; isActive: boolean }
export interface ItemTypeConfig { code: string; label: string; isActive: boolean; categories: ItemCategory[] }

export const BASE_UNITS = ['pcs', 'kg', 'gram', 'liter', 'ml', 'meter', 'sheet', 'roll', 'set', 'bottle', 'can']
export const PURCHASE_UNITS = ['pcs', 'box', 'carton', 'dozen', 'sack', 'drum', 'gallon', 'bottle', 'can', 'pack', 'kg', 'liter']

export const EMPTY_ITEM_FORM = {
  sku: '', name: '', type: '', category: '',
  baseUnit: 'pcs', purchaseUnit: 'pcs', conversionFactor: 1,
  standardCost: 0, sellingPrice: 0, valuationMethod: 'FIFO',
  minStock: 0, reorderQty: 0, imageKey: null as string | null,
  isSoldInPos: true, isStockTracked: true,
}
export type ItemForm = typeof EMPTY_ITEM_FORM

export function generateSku(prefix: string, existingItems: { sku: string }[]): string {
  const nums = existingItems
    .map(i => i.sku)
    .filter(s => s.startsWith(prefix + '-'))
    .map(s => parseInt(s.split('-').pop() ?? '0', 10))
    .filter(n => !isNaN(n))
  const next = nums.length > 0 ? Math.max(...nums) + 1 : 1
  return `${prefix}-${String(next).padStart(2, '0')}`
}

function calcMargin(cost: number, price: number) {
  return price > 0 ? ((price - cost) / price) * 100 : 0
}
function calcPriceFromMargin(cost: number, margin: number) {
  return margin >= 100 ? 0 : cost / (1 - margin / 100)
}

function categoriesFor(typeConfigs: ItemTypeConfig[], type: string) {
  return typeConfigs.find(t => t.code === type)?.categories.filter(c => c.isActive).map(c => c.name) ?? []
}
function skuPrefixFor(typeConfigs: ItemTypeConfig[], type: string, category: string) {
  return typeConfigs.find(t => t.code === type)?.categories.find(c => c.name === category)?.skuPrefix ?? ''
}

/** Fresh Add-form: first active type, its first category, and an auto-generated SKU. */
export function newItemForm(typeConfigs: ItemTypeConfig[], existingItems: { sku: string }[]): ItemForm {
  const type = typeConfigs.find(t => t.isActive)?.code ?? ''
  const category = categoriesFor(typeConfigs, type)[0] ?? ''
  const prefix = skuPrefixFor(typeConfigs, type, category)
  return { ...EMPTY_ITEM_FORM, type, category, sku: prefix ? generateSku(prefix, existingItems) : '' }
}

export function ItemFormFields({ form, setForm, isEditing, typeConfigs, existingItems, skuAutoGenerated, setSkuAutoGenerated }: {
  form: ItemForm
  setForm: Dispatch<SetStateAction<ItemForm>>
  isEditing: boolean
  typeConfigs: ItemTypeConfig[]
  existingItems: { sku: string }[]
  skuAutoGenerated: boolean
  setSkuAutoGenerated: (v: boolean) => void
}) {
  const activeTypes = typeConfigs.filter(t => t.isActive)

  const processProductImage = (file: File) => {
    const canvas = document.createElement('canvas')
    const img = new window.Image()
    img.onload = () => {
      const MAX = 800
      const scale = Math.min(1, MAX / Math.max(img.width, img.height))
      canvas.width = img.width * scale; canvas.height = img.height * scale
      canvas.getContext('2d')!.drawImage(img, 0, 0, canvas.width, canvas.height)
      setForm(f => ({ ...f, imageKey: canvas.toDataURL('image/jpeg', 0.8) }))
    }
    img.src = URL.createObjectURL(file)
  }
  const { isDragging: isDraggingProductImage, dropProps: productImageDropProps } = useFileDrop(files => { if (files[0]) processProductImage(files[0]) })

  const f2 = 'w-full h-9 border rounded-md px-3 text-sm focus:outline-none focus:ring-1 focus:ring-amber-500 bg-white'
  const num = `${f2} [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none`
  const typeCategories = categoriesFor(typeConfigs, form.type)

  return (
    <>
      {/* Product Image */}
      <div className="space-y-1.5">
        <label className="text-sm font-medium">Product Image <span className="text-muted-foreground font-normal">(optional)</span></label>
        <div {...productImageDropProps} className={`flex items-center gap-3 rounded-lg p-1.5 -m-1.5 transition-colors ${isDraggingProductImage ? 'ring-2 ring-amber-400 bg-amber-50' : ''}`}>
          {form.imageKey ? (
            <div className="relative shrink-0">
              <img src={form.imageKey} alt="Product" className="w-20 h-20 rounded-lg object-cover border" />
              <button type="button" onClick={() => setForm(f => ({ ...f, imageKey: null }))}
                className="absolute -top-1.5 -right-1.5 w-5 h-5 rounded-full bg-destructive text-white flex items-center justify-center text-xs">×</button>
            </div>
          ) : (
            <div className="w-20 h-20 rounded-lg border-2 border-dashed border-muted flex items-center justify-center text-muted-foreground shrink-0">
              <Package className="h-6 w-6 opacity-40" />
            </div>
          )}
          <label className="cursor-pointer flex-1">
            <div className="flex items-center gap-2 border rounded-md px-3 py-2 text-sm text-muted-foreground hover:bg-muted/50 transition-colors">
              <Upload className="h-4 w-4" />
              <span>{isDraggingProductImage ? 'Drop to upload' : form.imageKey ? 'Change photo' : 'Upload or drag photo'}</span>
            </div>
            <input type="file" accept="image/*" className="hidden" onChange={e => {
              const file = e.target.files?.[0]
              if (!file) return
              processProductImage(file)
              e.target.value = ''
            }} />
          </label>
        </div>
      </div>

      <div className="space-y-1.5">
        <label className="text-sm font-medium">Type *</label>
        <div className="grid grid-cols-3 gap-2">
          {activeTypes.map(t => {
            const Icon = getTypeIcon(t.code)
            return (
              <button key={t.code} type="button" onClick={() => {
                const type = t.code
                const category = categoriesFor(typeConfigs, type)[0] ?? ''
                const prefix = skuPrefixFor(typeConfigs, type, category)
                setForm(f => ({
                  ...f, type, category,
                  ...(skuAutoGenerated && prefix ? { sku: generateSku(prefix, existingItems) } : {}),
                }))
              }} className={`w-full h-10 flex items-center justify-center gap-1.5 rounded-md text-sm font-medium border transition-colors ${form.type === t.code ? 'bg-amber-600 text-white border-amber-600' : 'bg-white text-muted-foreground border-input hover:bg-muted'}`}>
                <Icon className="h-4 w-4" /> {t.label}
              </button>
            )
          })}
        </div>
      </div>

      {/* Non-Stock Item creation has moved to the Inventory module — this form
          only ever creates/edits Stock Items now (isStockTracked always true,
          see EMPTY_ITEM_FORM). */}

      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <label className="text-sm font-medium">SKU *</label>
            {!isEditing && (
              <button type="button"
                onClick={() => {
                  const prefix = skuPrefixFor(typeConfigs, form.type, form.category)
                  if (!prefix) return
                  const sku = generateSku(prefix, existingItems)
                  setForm(f => ({ ...f, sku }))
                  setSkuAutoGenerated(true)
                }}
                className="text-xs text-[#bdac7e] hover:text-[#a89860] font-medium transition-colors">
                ↻ Generate
              </button>
            )}
          </div>
          <input
            className={`${f2} uppercase font-mono`}
            placeholder={`${skuPrefixFor(typeConfigs, form.type, form.category) || 'SKU'}-01`}
            value={form.sku}
            onChange={e => { setSkuAutoGenerated(false); setForm(f => ({ ...f, sku: e.target.value })) }} />
          {skuAutoGenerated && <p className="text-xs text-muted-foreground">Auto-generated · ubah tipe untuk update</p>}
        </div>
        <div className="space-y-1.5">
          <label className="text-sm font-medium">Category *</label>
          <select className={f2} value={form.category} onChange={e => {
            const category = e.target.value
            const prefix = skuPrefixFor(typeConfigs, form.type, category)
            setForm(f => ({
              ...f, category,
              ...(skuAutoGenerated && prefix ? { sku: generateSku(prefix, existingItems) } : {}),
            }))
          }}>
            {/* A promoted non-stock item (or one created on the fly in Stock Opname Awal)
                may carry a category not present in the configured list — keep it
                selectable so saving here doesn't silently overwrite it with whatever
                option happens to be first. */}
            {(typeCategories.includes(form.category) || !form.category
              ? typeCategories
              : [form.category, ...typeCategories]
            ).map(c => <option key={c}>{c}</option>)}
          </select>
        </div>
      </div>
      <div className="space-y-1.5">
        <label className="text-sm font-medium">Item Name *</label>
        <input className={f2} placeholder="Premium Rice" value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))} />
      </div>
      <div className="grid grid-cols-3 gap-4">
        <div className="space-y-1.5">
          <label className="text-sm font-medium">Base Unit *</label>
          <select className={f2} value={form.baseUnit} onChange={e => setForm(f => ({ ...f, baseUnit: e.target.value }))}>
            {(BASE_UNITS.includes(form.baseUnit) ? BASE_UNITS : [form.baseUnit, ...BASE_UNITS]).map(u => <option key={u}>{u}</option>)}
          </select>
        </div>
        <div className="space-y-1.5">
          <label className="text-sm font-medium">Purchase Unit *</label>
          <select className={f2} value={form.purchaseUnit} onChange={e => setForm(f => ({ ...f, purchaseUnit: e.target.value }))}>
            {(PURCHASE_UNITS.includes(form.purchaseUnit) ? PURCHASE_UNITS : [form.purchaseUnit, ...PURCHASE_UNITS]).map(u => <option key={u}>{u}</option>)}
          </select>
        </div>
        <div className="space-y-1.5">
          <label className="text-sm font-medium">Conversion</label>
          <input type="number" min={1} className={num} value={form.conversionFactor} onChange={e => setForm(f => ({ ...f, conversionFactor: Number(e.target.value) }))} />
          <p className="text-xs text-muted-foreground">1 {form.purchaseUnit} = {form.conversionFactor} {form.baseUnit}</p>
        </div>
      </div>
      {/* Pricing section */}
      <div className="border-t pt-4">
        <div className="flex items-center justify-between mb-3">
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Pricing & Valuation</p>
          <button
            type="button"
            onClick={() => setForm(f => ({ ...f, isSoldInPos: !f.isSoldInPos }))}
            className="flex items-center gap-1.5 text-xs font-medium text-muted-foreground hover:text-foreground transition-colors"
          >
            Sold in POS
            {form.isSoldInPos
              ? <ToggleRight className="h-5 w-5 text-green-600" />
              : <ToggleLeft className="h-5 w-5" />}
          </button>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-1.5">
            <label className="text-sm font-medium">Last Purchase Cost <span className="text-muted-foreground font-normal">/ {form.baseUnit}</span></label>
            <input
              type="number" readOnly
              className={`${num} bg-muted/40 cursor-not-allowed text-muted-foreground`}
              value={form.standardCost || ''} placeholder="—" />
            <p className="text-xs text-muted-foreground">Auto-updated from actual received price (GR). Stock is valued at moving average cost.</p>
          </div>
          {form.isSoldInPos && (
            <div className="space-y-1.5">
              <label className="text-sm font-medium">Selling Price <span className="text-muted-foreground font-normal">/ {form.baseUnit}</span></label>
              <input type="number" min={0} className={num} placeholder="0"
                value={form.sellingPrice}
                onChange={e => {
                  const sellingPrice = Number(e.target.value)
                  setForm(f => ({ ...f, sellingPrice }))
                }} />
            </div>
          )}
          {form.isSoldInPos && (
            <div className="space-y-1.5">
              <label className="text-sm font-medium">Gross Margin %</label>
              <input type="number" step="0.1" min={0} max={99.9} className={num} placeholder="0"
                value={form.sellingPrice > 0 ? +calcMargin(form.standardCost, form.sellingPrice).toFixed(1) : ''}
                onChange={e => {
                  const margin = Number(e.target.value)
                  const sellingPrice = calcPriceFromMargin(form.standardCost, margin)
                  setForm(f => ({ ...f, sellingPrice: Math.round(sellingPrice) }))
                }} />
              <p className="text-xs text-muted-foreground">Auto-synced with Selling Price</p>
            </div>
          )}
        </div>
      </div>

      {/* Stock control section — meaningless for non-stock items, which never
          accumulate a stock balance to reorder against. */}
      {form.isStockTracked && (
        <div className="border-t pt-4">
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Stock Control</p>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <label className="text-sm font-medium">Min Stock</label>
              <input type="number" min={0} className={num} placeholder="0" value={form.minStock} onChange={e => setForm(f => ({ ...f, minStock: Number(e.target.value) }))} />
            </div>
            <div className="space-y-1.5">
              <label className="text-sm font-medium">Reorder Qty</label>
              <input type="number" min={0} className={num} placeholder="0" value={form.reorderQty} onChange={e => setForm(f => ({ ...f, reorderQty: Number(e.target.value) }))} />
            </div>
          </div>
        </div>
      )}
    </>
  )
}
