'use client'

import { useState, useEffect, useCallback, useRef } from 'react'
import { Plus, Search, Pencil, Trash2, ToggleLeft, ToggleRight, X, Download, Upload, FileDown, CheckCircle2, AlertCircle, History, ArrowRight, ArrowLeft, Package, ChevronRight, Layers, UtensilsCrossed, Wine, Wrench, type LucideIcon } from 'lucide-react'
import { sortByMethod, computeStockValue, methodLabel, type ValuationMethod } from '@/lib/valuation'
import { ITEM_TYPES, ITEM_TYPE_LABELS, TYPE_CATEGORIES, SKU_PREFIX, type PurchaseItemType } from '@/lib/purchase-item-types'

const ITEM_TYPE_ICON: Record<PurchaseItemType, LucideIcon> = {
  FOOD: UtensilsCrossed,
  BEVERAGE: Wine,
  SPAREPART: Wrench,
}

interface PurchaseItem {
  id: string
  sku: string
  name: string
  type: PurchaseItemType
  category: string
  baseUnit: string
  purchaseUnit: string
  conversionFactor: number
  standardCost: number
  sellingPrice: number
  valuationMethod: string
  minStock: number
  reorderQty: number
  imageKey: string | null
  isActive: boolean
  totalQty: number
  avgPrice: number
}

const BASE_UNITS = ['pcs', 'kg', 'gram', 'liter', 'ml', 'meter', 'sheet', 'roll', 'set', 'bottle', 'can']
const PURCHASE_UNITS = ['pcs', 'box', 'carton', 'dozen', 'sack', 'drum', 'gallon', 'bottle', 'can', 'pack', 'kg', 'liter']

const VALUATION_METHODS = ['FIFO', 'LIFO', 'WEIGHTED_AVERAGE', 'STANDARD']

function generateSku(type: PurchaseItemType, existingItems: PurchaseItem[]): string {
  const prefix = SKU_PREFIX[type]
  const nums = existingItems
    .map(i => i.sku)
    .filter(s => s.startsWith(prefix + '-'))
    .map(s => parseInt(s.split('-').pop() ?? '0', 10))
    .filter(n => !isNaN(n))
  const next = nums.length > 0 ? Math.max(...nums) + 1 : 1
  return `${prefix}-${String(next).padStart(3, '0')}`
}

const EMPTY_FORM = {
  sku: '', name: '', type: 'SPAREPART' as PurchaseItemType, category: TYPE_CATEGORIES.SPAREPART[0],
  baseUnit: 'pcs', purchaseUnit: 'pcs', conversionFactor: 1,
  standardCost: 0, sellingPrice: 0, valuationMethod: 'FIFO',
  minStock: 0, reorderQty: 0, imageKey: null as string | null,
}

function calcMargin(cost: number, price: number) {
  return price > 0 ? ((price - cost) / price) * 100 : 0
}
function calcPriceFromMargin(cost: number, margin: number) {
  return margin >= 100 ? 0 : cost / (1 - margin / 100)
}

interface HistoryEntry {
  id: string; date: string; type: string; qty: number; unit: string
  fromLocation: string | null; toLocation: string | null
  notes: string | null; by: string | null
  unitCost: number | null; supplier: string | null
  poNumber: string | null; grNumber: string | null
}
interface StockEntry { locationId: string; locationName: string; locationType: string; qty: number; costPerUnit: number }
interface LotEntry { id: string; locationId: string; locationName: string; quantity: number; costPerUnit: number; batch: string | null; expiresAt: string | null; createdAt: string }

const CSV_HEADERS = ['SKU', 'Name', 'Type', 'Category', 'Base Unit', 'Purchase Unit', 'Conversion', 'Standard Cost', 'Selling Price', 'Valuation Method', 'Min Stock', 'Reorder Qty']

function fmt(n: number) {
  return new Intl.NumberFormat('id-ID').format(n)
}

function buildCSV(rows: string[][]): string {
  return rows.map(r => r.map(v => `"${String(v).replace(/"/g, '""')}"`).join(',')).join('\n')
}

function downloadFile(content: string, filename: string, mime = 'text/csv;charset=utf-8;') {
  const blob = new Blob(['﻿' + content, ], { type: mime }) // BOM for Excel UTF-8
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = filename; a.click()
  URL.revokeObjectURL(url)
}

export default function ItemsPage() {
  const [items, setItems] = useState<PurchaseItem[]>([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const [typeFilter, setTypeFilter] = useState<'All' | PurchaseItemType>('All')
  const [catFilter, setCatFilter] = useState('All')
  const [modal, setModal] = useState<{ open: boolean; editing: PurchaseItem | null }>({ open: false, editing: null })
  const [form, setForm] = useState(EMPTY_FORM)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [skuAutoGenerated, setSkuAutoGenerated] = useState(false)
  const [deleteConfirm, setDeleteConfirm] = useState<PurchaseItem | null>(null)
  const [importing, setImporting] = useState(false)
  const [importResult, setImportResult] = useState<{ imported: number; updated: number; total: number; errors: { row: number; sku: string; error: string }[] } | null>(null)
  const importRef = useRef<HTMLInputElement>(null)

  // History panel
  const [historyItem, setHistoryItem] = useState<PurchaseItem | null>(null)
  const [historyData, setHistoryData] = useState<{ timeline: HistoryEntry[]; currentStock: StockEntry[]; lots: LotEntry[]; valuationMethod: string; standardCost: number } | null>(null)
  const [historyLoading, setHistoryLoading] = useState(false)

  async function openHistory(item: PurchaseItem) {
    setHistoryItem(item)
    setHistoryData(null)
    setHistoryLoading(true)
    const res = await fetch(`/api/purchasing/items/${item.id}/history`)
    if (res.ok) setHistoryData(await res.json())
    setHistoryLoading(false)
  }

  const load = useCallback(async () => {
    setLoading(true)
    const res = await fetch('/api/purchasing/items')
    if (res.ok) setItems(await res.json())
    setLoading(false)
  }, [])

  useEffect(() => { load() }, [load])

  function openAdd() {
    const sku = generateSku(EMPTY_FORM.type, items)
    setForm({ ...EMPTY_FORM, sku })
    setSkuAutoGenerated(true)
    setError('')
    setModal({ open: true, editing: null })
  }

  function openEdit(item: PurchaseItem) {
    setSkuAutoGenerated(false)
    setForm({
      sku: item.sku,
      name: item.name,
      type: item.type,
      category: item.category,
      baseUnit: item.baseUnit,
      purchaseUnit: item.purchaseUnit,
      conversionFactor: item.conversionFactor,
      standardCost: item.standardCost,
      sellingPrice: item.sellingPrice,
      valuationMethod: item.valuationMethod,
      minStock: item.minStock,
      reorderQty: item.reorderQty,
      imageKey: item.imageKey,
    })
    setError('')
    setModal({ open: true, editing: item })
  }

  async function save() {
    setSaving(true)
    setError('')
    const method = modal.editing ? 'PUT' : 'POST'
    const url = modal.editing ? `/api/purchasing/items/${modal.editing.id}` : '/api/purchasing/items'
    const res = await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) })
    const data = await res.json()
    if (!res.ok) { setError(data.error ?? 'An error occurred'); setSaving(false); return }
    setModal({ open: false, editing: null })
    setSaving(false)
    load()
  }

  async function toggleActive(item: PurchaseItem) {
    await fetch(`/api/purchasing/items/${item.id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ ...item, isActive: !item.isActive }),
    })
    load()
  }

  async function doDelete(item: PurchaseItem) {
    const res = await fetch(`/api/purchasing/items/${item.id}`, { method: 'DELETE' })
    if (!res.ok) {
      const d = await res.json()
      alert(d.error ?? 'Failed to delete')
    }
    setDeleteConfirm(null)
    load()
  }

  function exportCSV() {
    const rows = items.map(i => [i.sku, i.name, i.type, i.category, i.baseUnit, i.purchaseUnit, String(i.conversionFactor), String(i.standardCost), String(i.sellingPrice), i.valuationMethod, String(i.minStock), String(i.reorderQty)])
    downloadFile(buildCSV([CSV_HEADERS, ...rows]), `item-master-${new Date().toISOString().slice(0, 10)}.csv`)
  }

  function downloadTemplate() {
    const sample = ['FOOD-001', 'Premium Rice', 'FOOD', 'Dry Food', 'kg', 'sack', '25', '22000', '0', 'FIFO', '12', '50']
    downloadFile(buildCSV([CSV_HEADERS, sample]), 'template-item-master.csv')
  }

  async function handleImportFile(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    e.target.value = ''
    setImporting(true)
    setImportResult(null)
    const fd = new FormData()
    fd.append('file', file)
    const res = await fetch('/api/purchasing/items/import', { method: 'POST', body: fd })
    const data = await res.json()
    setImporting(false)
    if (!res.ok) { alert(data.error ?? 'Import failed'); return }
    setImportResult(data)
    load()
  }

  const filtered = items.filter(i => {
    const matchType = typeFilter === 'All' || i.type === typeFilter
    const matchCat = catFilter === 'All' || i.category === catFilter
    const matchSearch = !search || i.name.toLowerCase().includes(search.toLowerCase()) || i.sku.toLowerCase().includes(search.toLowerCase())
    return matchType && matchCat && matchSearch
  })

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">Item Master</h2>
          <p className="text-muted-foreground text-sm mt-1">Item catalog, units, and standard costs</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={downloadTemplate}
            className="flex items-center gap-2 text-sm border rounded-md px-3 py-2 text-muted-foreground hover:bg-muted transition-colors"
            title="Download template CSV"
          >
            <FileDown className="h-4 w-4" /> Template
          </button>
          <button
            onClick={exportCSV}
            disabled={items.length === 0}
            className="flex items-center gap-2 text-sm border rounded-md px-3 py-2 text-muted-foreground hover:bg-muted disabled:opacity-40 transition-colors"
          >
            <Download className="h-4 w-4" /> Export CSV
          </button>
          <button
            onClick={() => importRef.current?.click()}
            disabled={importing}
            className="flex items-center gap-2 text-sm border rounded-md px-3 py-2 text-muted-foreground hover:bg-muted disabled:opacity-40 transition-colors"
          >
            <Upload className="h-4 w-4" /> {importing ? 'Importing...' : 'Import CSV'}
          </button>
          <input ref={importRef} type="file" accept=".csv,text/csv" className="hidden" onChange={handleImportFile} />
          <button
            onClick={openAdd}
            className="flex items-center gap-2 bg-amber-600 hover:bg-amber-700 text-white text-sm font-medium px-4 py-2 rounded-md transition-colors"
          >
            <Plus className="h-4 w-4" /> Add
          </button>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap items-center gap-2.5 rounded-lg border bg-muted/20 px-3 py-2.5">
        <div className="relative flex-1 min-w-[180px] max-w-xs">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground pointer-events-none" />
          <input
            className="w-full h-9 pl-9 pr-3 text-sm border rounded-md bg-background focus:outline-none focus:ring-1 focus:ring-amber-500"
            placeholder="Search name or SKU..."
            value={search}
            onChange={e => setSearch(e.target.value)}
          />
        </div>

        <div className="h-6 w-px bg-border hidden sm:block" />

        {/* Type tabs */}
        <div className="flex gap-1 bg-muted rounded-md p-1">
          <button
            onClick={() => { setTypeFilter('All'); setCatFilter('All') }}
            className={`px-2.5 py-1 rounded text-xs font-medium transition-colors ${typeFilter === 'All' ? 'bg-white shadow-sm text-foreground' : 'text-muted-foreground hover:text-foreground'}`}
          >
            All
          </button>
          {ITEM_TYPES.map(t => {
            const Icon = ITEM_TYPE_ICON[t]
            return (
              <button
                key={t}
                onClick={() => { setTypeFilter(t); setCatFilter('All') }}
                className={`flex items-center gap-1.5 px-2.5 py-1 rounded text-xs font-medium transition-colors whitespace-nowrap ${typeFilter === t ? 'bg-white shadow-sm text-foreground' : 'text-muted-foreground hover:text-foreground'}`}
              >
                <Icon className="h-3.5 w-3.5" /> {ITEM_TYPE_LABELS[t]}
              </button>
            )
          })}
        </div>

        {/* Category — scoped to selected type */}
        {typeFilter !== 'All' && (
          <select
            value={catFilter}
            onChange={e => setCatFilter(e.target.value)}
            className="h-9 border rounded-md px-2.5 text-sm bg-background focus:outline-none focus:ring-1 focus:ring-amber-500"
          >
            <option value="All">All Categories</option>
            {TYPE_CATEGORIES[typeFilter].map(c => <option key={c} value={c}>{c}</option>)}
          </select>
        )}

        {(search || typeFilter !== 'All') && (
          <button
            onClick={() => { setSearch(''); setTypeFilter('All'); setCatFilter('All') }}
            className="text-xs text-muted-foreground hover:text-foreground transition-colors ml-auto"
          >
            Reset
          </button>
        )}
      </div>

      {/* Table */}
      <div className="rounded-lg border overflow-hidden">
        <table className="w-full text-sm">
          <thead className="bg-muted/50 text-xs text-muted-foreground">
            <tr>
              <th className="text-left px-4 py-3 font-medium w-24">SKU</th>
              <th className="text-left px-4 py-3 font-medium">Name</th>
              <th className="text-left px-4 py-3 font-medium w-28">Unit</th>
              <th className="text-right px-4 py-3 font-medium w-36">Cost / Price</th>
              <th className="text-right px-4 py-3 font-medium w-20">Margin</th>
              <th className="text-left px-4 py-3 font-medium w-28">Valuation</th>
              <th className="text-right px-4 py-3 font-medium w-28">Stock</th>
              <th className="text-center px-4 py-3 font-medium w-16">Status</th>
              <th className="px-4 py-3 w-20" />
            </tr>
          </thead>
          <tbody className="divide-y">
            {loading ? (
              <>
                {[...Array(6)].map((_, i) => (
                  <tr key={i} className="border-t">
                    {[...Array(9)].map((_, j) => (
                      <td key={j} className="px-4 py-3.5"><div className="h-3.5 w-full rounded bg-muted animate-pulse" /></td>
                    ))}
                  </tr>
                ))}
              </>
            ) : filtered.length === 0 ? (
              <tr><td colSpan={9} className="text-center py-12 text-muted-foreground text-sm">
                {search || catFilter !== 'All' ? 'No results found' : 'No items yet. Click "Add" to get started.'}
              </td></tr>
            ) : filtered.map(item => {
              const margin = calcMargin(item.standardCost, item.sellingPrice)
              return (
                <tr key={item.id} onClick={() => openHistory(item)} className={`hover:bg-amber-50/40 cursor-pointer transition-colors ${!item.isActive ? 'opacity-50' : ''}`}>
                  <td className="px-4 py-3 font-mono text-xs text-muted-foreground whitespace-nowrap">{item.sku}</td>
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-2.5 min-w-0">
                      {item.imageKey ? (
                        <img src={item.imageKey} alt={item.name} className="w-9 h-9 rounded-lg object-cover shrink-0 border" />
                      ) : (
                        <div className="w-9 h-9 rounded-lg bg-muted flex items-center justify-center shrink-0">
                          <Package className="h-4 w-4 text-muted-foreground opacity-40" />
                        </div>
                      )}
                      <div className="min-w-0">
                        <p className="font-medium truncate">{item.name}</p>
                        <div className="flex items-center gap-1">
                          <span className="flex items-center gap-1 text-[10px] px-1.5 py-0.5 rounded-full bg-amber-50 text-amber-700">
                            {(() => { const Icon = ITEM_TYPE_ICON[item.type]; return <Icon className="h-2.5 w-2.5" /> })()} {ITEM_TYPE_LABELS[item.type]}
                          </span>
                          <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-muted text-muted-foreground">{item.category}</span>
                        </div>
                      </div>
                    </div>
                  </td>
                  <td className="px-4 py-3 text-sm text-muted-foreground whitespace-nowrap">
                    <span className="font-medium text-foreground">{item.baseUnit}</span>
                    {item.purchaseUnit !== item.baseUnit && (
                      <p className="text-[10px] text-muted-foreground">{item.conversionFactor}× / {item.purchaseUnit}</p>
                    )}
                  </td>
                  <td className="px-4 py-3 text-right">
                    <p className="text-sm font-medium">{item.standardCost > 0 ? `Rp ${fmt(Math.round(item.standardCost))}` : <span className="text-muted-foreground font-normal">—</span>}</p>
                    {item.sellingPrice > 0 && <p className="text-xs text-muted-foreground">sell {fmt(Math.round(item.sellingPrice))}</p>}
                  </td>
                  <td className="px-4 py-3 text-right">
                    {item.sellingPrice > 0
                      ? <span className={`text-xs font-semibold ${margin >= 40 ? 'text-green-600' : margin >= 20 ? 'text-amber-600' : 'text-red-500'}`}>{margin.toFixed(1)}%</span>
                      : <span className="text-muted-foreground text-xs">—</span>}
                  </td>
                  <td className="px-4 py-3">
                    <span className="text-xs px-2 py-0.5 rounded-full bg-blue-50 text-blue-700 font-medium whitespace-nowrap">
                      {item.valuationMethod === 'WEIGHTED_AVERAGE' ? 'WA' : item.valuationMethod}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-right">
                    {item.totalQty > 0
                      ? <span className="font-medium text-sm">{fmt(item.totalQty)} <span className="text-muted-foreground font-normal text-xs">{item.baseUnit}</span></span>
                      : <span className="text-muted-foreground text-xs">—</span>}
                  </td>
                  <td className="px-4 py-3 text-center">
                    <button onClick={e => { e.stopPropagation(); toggleActive(item) }} className="text-muted-foreground hover:text-foreground transition-colors" title={item.isActive ? 'Deactivate' : 'Activate'}>
                      {item.isActive
                        ? <ToggleRight className="h-5 w-5 text-green-600" />
                        : <ToggleLeft className="h-5 w-5" />}
                    </button>
                  </td>
                  <td className="px-4 py-3" onClick={e => e.stopPropagation()}>
                    <div className="flex items-center gap-2 justify-end">
                      <button onClick={() => openEdit(item)} className="text-muted-foreground hover:text-foreground transition-colors">
                        <Pencil className="h-4 w-4" />
                      </button>
                      <button onClick={() => setDeleteConfirm(item)} className="text-muted-foreground hover:text-destructive transition-colors">
                        <Trash2 className="h-4 w-4" />
                      </button>
                      <ChevronRight className="h-4 w-4 text-muted-foreground/40" />
                    </div>
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>

      <p className="text-xs text-muted-foreground">{filtered.length} of {items.length} items</p>

      {/* Add/Edit Modal */}
      {modal.open && (
        <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-lg max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between p-6 border-b">
              <h3 className="font-semibold text-lg">{modal.editing ? 'Edit Item' : 'Add Item'}</h3>
              <button onClick={() => setModal({ open: false, editing: null })} className="text-muted-foreground hover:text-foreground">
                <X className="h-5 w-5" />
              </button>
            </div>
            {(() => {
              const f2 = 'w-full h-9 border rounded-md px-3 text-sm focus:outline-none focus:ring-1 focus:ring-amber-500 bg-white'
              const num = `${f2} [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none`
              return (
                <div className="p-6 space-y-4">
                  {error && <p className="text-sm text-destructive bg-destructive/10 rounded-md px-3 py-2">{error}</p>}

                  {/* Product Image */}
                  <div className="space-y-1.5">
                    <label className="text-sm font-medium">Product Image <span className="text-muted-foreground font-normal">(optional)</span></label>
                    <div className="flex items-center gap-3">
                      {form.imageKey ? (
                        <div className="relative shrink-0">
                          <img src={form.imageKey} alt="Product" className="w-20 h-20 rounded-lg object-cover border" />
                          <button type="button" onClick={() => setForm(f => ({ ...f, imageKey: null }))}
                            className="absolute -top-1.5 -right-1.5 w-5 h-5 rounded-full bg-destructive text-white flex items-center justify-center text-xs">×</button>
                        </div>
                      ) : (
                        <div className="w-20 h-20 rounded-lg border-2 border-dashed border-muted flex items-center justify-center text-muted-foreground shrink-0">
                          <Package className="h-6 w-6 opacity-40" />
                        </div>
                      )}
                      <label className="cursor-pointer flex-1">
                        <div className="flex items-center gap-2 border rounded-md px-3 py-2 text-sm text-muted-foreground hover:bg-muted/50 transition-colors">
                          <Upload className="h-4 w-4" />
                          <span>{form.imageKey ? 'Change photo' : 'Upload photo'}</span>
                        </div>
                        <input type="file" accept="image/*" className="hidden" onChange={e => {
                          const file = e.target.files?.[0]
                          if (!file) return
                          const canvas = document.createElement('canvas')
                          const img = new window.Image()
                          img.onload = () => {
                            const MAX = 800
                            const scale = Math.min(1, MAX / Math.max(img.width, img.height))
                            canvas.width = img.width * scale; canvas.height = img.height * scale
                            canvas.getContext('2d')!.drawImage(img, 0, 0, canvas.width, canvas.height)
                            setForm(f => ({ ...f, imageKey: canvas.toDataURL('image/jpeg', 0.8) }))
                          }
                          img.src = URL.createObjectURL(file)
                          e.target.value = ''
                        }} />
                      </label>
                    </div>
                  </div>

                  <div className="space-y-1.5">
                    <label className="text-sm font-medium">Type *</label>
                    <div className="flex gap-2">
                      {ITEM_TYPES.map(t => {
                        const Icon = ITEM_TYPE_ICON[t]
                        return (
                          <button key={t} type="button" onClick={() => {
                            const type = t
                            const category = TYPE_CATEGORIES[type][0]
                            setForm(f => ({
                              ...f, type, category,
                              ...(skuAutoGenerated ? { sku: generateSku(type, items) } : {}),
                            }))
                          }} className={`flex-1 h-9 flex items-center justify-center gap-1.5 rounded-md text-sm font-medium border transition-colors ${form.type === t ? 'bg-amber-600 text-white border-amber-600' : 'bg-white text-muted-foreground border-input hover:bg-muted'}`}>
                            <Icon className="h-4 w-4" /> {ITEM_TYPE_LABELS[t]}
                          </button>
                        )
                      })}
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <div className="flex items-center justify-between">
                        <label className="text-sm font-medium">SKU *</label>
                        {!modal.editing && (
                          <button type="button"
                            onClick={() => { const sku = generateSku(form.type, items); setForm(f => ({ ...f, sku })); setSkuAutoGenerated(true) }}
                            className="text-xs text-[#bdac7e] hover:text-[#a89860] font-medium transition-colors">
                            ↻ Generate
                          </button>
                        )}
                      </div>
                      <input
                        className={`${f2} uppercase font-mono`}
                        placeholder={`${SKU_PREFIX[form.type]}-001`}
                        value={form.sku}
                        onChange={e => { setSkuAutoGenerated(false); setForm(f => ({ ...f, sku: e.target.value })) }} />
                      {skuAutoGenerated && <p className="text-xs text-muted-foreground">Auto-generated · ubah tipe untuk update</p>}
                    </div>
                    <div className="space-y-1.5">
                      <label className="text-sm font-medium">Category *</label>
                      <select className={f2} value={form.category} onChange={e => setForm(f => ({ ...f, category: e.target.value }))}>
                        {TYPE_CATEGORIES[form.type].map(c => <option key={c}>{c}</option>)}
                      </select>
                    </div>
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-sm font-medium">Item Name *</label>
                    <input className={f2} placeholder="Premium Rice" value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))} />
                  </div>
                  <div className="grid grid-cols-3 gap-4">
                    <div className="space-y-1.5">
                      <label className="text-sm font-medium">Base Unit *</label>
                      <select className={f2} value={form.baseUnit} onChange={e => setForm(f => ({ ...f, baseUnit: e.target.value }))}>
                        {BASE_UNITS.map(u => <option key={u}>{u}</option>)}
                      </select>
                    </div>
                    <div className="space-y-1.5">
                      <label className="text-sm font-medium">Purchase Unit *</label>
                      <select className={f2} value={form.purchaseUnit} onChange={e => setForm(f => ({ ...f, purchaseUnit: e.target.value }))}>
                        {PURCHASE_UNITS.map(u => <option key={u}>{u}</option>)}
                      </select>
                    </div>
                    <div className="space-y-1.5">
                      <label className="text-sm font-medium">Conversion</label>
                      <input type="number" min={1} className={num} value={form.conversionFactor} onChange={e => setForm(f => ({ ...f, conversionFactor: Number(e.target.value) }))} />
                      <p className="text-xs text-muted-foreground">1 {form.purchaseUnit} = {form.conversionFactor} {form.baseUnit}</p>
                    </div>
                  </div>
                  {/* Pricing section */}
                  <div className="border-t pt-4">
                    <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Pricing & Valuation</p>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-1.5">
                        <label className="text-sm font-medium">Standard Cost <span className="text-muted-foreground font-normal">/ {form.baseUnit}</span></label>
                        <input
                          type="number" readOnly
                          className={`${num} bg-muted/40 cursor-not-allowed text-muted-foreground`}
                          value={form.standardCost || ''} placeholder="—" />
                        <p className="text-xs text-muted-foreground">Auto-updated from actual received price (GR)</p>
                      </div>
                      <div className="space-y-1.5">
                        <label className="text-sm font-medium">Selling Price <span className="text-muted-foreground font-normal">/ {form.baseUnit}</span></label>
                        <input type="number" min={0} className={num} placeholder="0"
                          value={form.sellingPrice}
                          onChange={e => {
                            const sellingPrice = Number(e.target.value)
                            setForm(f => ({ ...f, sellingPrice }))
                          }} />
                      </div>
                      <div className="space-y-1.5">
                        <label className="text-sm font-medium">Gross Margin %</label>
                        <input type="number" step="0.1" min={0} max={99.9} className={num} placeholder="0"
                          value={form.sellingPrice > 0 ? +calcMargin(form.standardCost, form.sellingPrice).toFixed(1) : ''}
                          onChange={e => {
                            const margin = Number(e.target.value)
                            const sellingPrice = calcPriceFromMargin(form.standardCost, margin)
                            setForm(f => ({ ...f, sellingPrice: Math.round(sellingPrice) }))
                          }} />
                        <p className="text-xs text-muted-foreground">Auto-synced with Selling Price</p>
                      </div>
                      <div className="space-y-1.5">
                        <label className="text-sm font-medium">Valuation Method</label>
                        <select className={f2} value={form.valuationMethod} onChange={e => setForm(f => ({ ...f, valuationMethod: e.target.value }))}>
                          {VALUATION_METHODS.map(m => <option key={m} value={m}>{m.replace('_', ' ')}</option>)}
                        </select>
                      </div>
                    </div>
                  </div>

                  {/* Stock control section */}
                  <div className="border-t pt-4">
                    <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Stock Control</p>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-1.5">
                        <label className="text-sm font-medium">Min Stock</label>
                        <input type="number" min={0} className={num} placeholder="0" value={form.minStock} onChange={e => setForm(f => ({ ...f, minStock: Number(e.target.value) }))} />
                      </div>
                      <div className="space-y-1.5">
                        <label className="text-sm font-medium">Reorder Qty</label>
                        <input type="number" min={0} className={num} placeholder="0" value={form.reorderQty} onChange={e => setForm(f => ({ ...f, reorderQty: Number(e.target.value) }))} />
                      </div>
                    </div>
                  </div>
                </div>
              )
            })()}
            <div className="flex justify-end gap-3 px-6 py-4 border-t bg-muted/30">
              <button onClick={() => setModal({ open: false, editing: null })} className="px-4 py-2 text-sm border rounded-md hover:bg-muted transition-colors">Cancel</button>
              <button onClick={save} disabled={saving} className="px-4 py-2 text-sm bg-amber-600 text-white rounded-md hover:bg-amber-700 disabled:opacity-50 transition-colors font-medium">
                {saving ? 'Saving...' : modal.editing ? 'Save Changes' : 'Add Item'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Delete Confirm */}
      {deleteConfirm && (
        <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-sm p-6">
            <h3 className="font-semibold mb-2">Delete Item?</h3>
            <p className="text-sm text-muted-foreground mb-4">
              <span className="font-medium text-foreground">{deleteConfirm.name}</span> ({deleteConfirm.sku}) will be permanently deleted. This cannot be undone.
            </p>
            <div className="flex gap-3 justify-end">
              <button onClick={() => setDeleteConfirm(null)} className="px-4 py-2 text-sm border rounded-md hover:bg-muted transition-colors">Cancel</button>
              <button onClick={() => doDelete(deleteConfirm)} className="px-4 py-2 text-sm bg-destructive text-white rounded-md hover:bg-destructive/90 transition-colors">Delete</button>
            </div>
          </div>
        </div>
      )}

      {/* Import Result Modal */}
      {importResult && (
        <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-md">
            <div className="flex items-center justify-between p-6 border-b">
              <h3 className="font-semibold text-lg">CSV Import Results</h3>
              <button onClick={() => setImportResult(null)}><X className="h-5 w-5 text-muted-foreground" /></button>
            </div>
            <div className="p-6 space-y-4">
              <div className="grid grid-cols-3 gap-3">
                <div className="rounded-lg bg-green-50 border border-green-200 p-3 text-center">
                  <p className="text-2xl font-bold text-green-700">{importResult.imported}</p>
                  <p className="text-xs text-green-600 mt-0.5">New items</p>
                </div>
                <div className="rounded-lg bg-blue-50 border border-blue-200 p-3 text-center">
                  <p className="text-2xl font-bold text-blue-700">{importResult.updated}</p>
                  <p className="text-xs text-blue-600 mt-0.5">Updated</p>
                </div>
                <div className="rounded-lg bg-red-50 border border-red-200 p-3 text-center">
                  <p className="text-2xl font-bold text-red-700">{importResult.errors.length}</p>
                  <p className="text-xs text-red-600 mt-0.5">Error</p>
                </div>
              </div>

              {importResult.errors.length === 0 ? (
                <div className="flex items-center gap-2 text-green-700 bg-green-50 rounded-lg px-4 py-3">
                  <CheckCircle2 className="h-4 w-4 shrink-0" />
                  <p className="text-sm font-medium">All {importResult.total} rows processed successfully</p>
                </div>
              ) : (
                <div className="space-y-2">
                  <div className="flex items-center gap-2 text-amber-700 bg-amber-50 rounded-lg px-4 py-3">
                    <AlertCircle className="h-4 w-4 shrink-0" />
                    <p className="text-sm">{importResult.total} succeeded, {importResult.errors.length} rows failed:</p>
                  </div>
                  <div className="max-h-40 overflow-y-auto rounded-lg border divide-y text-sm">
                    {importResult.errors.map((e, i) => (
                      <div key={i} className="px-3 py-2 flex gap-3">
                        <span className="text-muted-foreground shrink-0">Row {e.row}</span>
                        <span className="font-mono text-xs shrink-0 text-amber-700">{e.sku}</span>
                        <span className="text-destructive text-xs">{e.error}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
            <div className="flex justify-end px-6 py-4 border-t bg-muted/30">
              <button onClick={() => setImportResult(null)} className="px-4 py-2 text-sm bg-amber-600 text-white rounded-md hover:bg-amber-700 font-medium transition-colors">
                Done
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Item History Modal ── */}
      {historyItem && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-4xl max-h-[88vh] flex flex-col">

            {/* Header */}
            <div className="flex items-center justify-between px-6 py-5 border-b shrink-0">
              <div className="flex items-center gap-3">
                {historyItem.imageKey ? (
                  <img src={historyItem.imageKey} alt={historyItem.name} className="w-12 h-12 rounded-xl object-cover border shrink-0" />
                ) : (
                  <div className="p-2 rounded-xl bg-amber-50 shrink-0">
                    <History className="h-5 w-5 text-amber-600" />
                  </div>
                )}
                <div>
                  <h3 className="font-bold text-lg">{historyItem.name}</h3>
                  <p className="text-xs text-muted-foreground font-mono mt-0.5">{historyItem.sku} · {ITEM_TYPE_LABELS[historyItem.type]} · {historyItem.category}</p>
                </div>
              </div>
              <button onClick={() => setHistoryItem(null)} className="p-2 hover:bg-muted rounded-lg transition-colors">
                <X className="h-5 w-5 text-muted-foreground" />
              </button>
            </div>

            <div className="overflow-y-auto flex-1 divide-y">
              {historyLoading ? (
                <div className="p-8 space-y-4 animate-pulse">
                  <div className="h-20 rounded-xl bg-muted/40" />
                  {[...Array(5)].map((_, i) => (
                    <div key={i} className="flex gap-3 py-2">
                      <div className="h-8 w-8 rounded-full bg-muted shrink-0" />
                      <div className="space-y-1.5 flex-1">
                        <div className="h-4 w-40 rounded bg-muted" />
                        <div className="h-3 w-56 rounded bg-muted" />
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <>
                  {/* Current stock */}
                  {(historyData?.currentStock?.length ?? 0) > 0 && (
                    <div className="px-6 py-4">
                      <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Current Stock</p>
                      <div className="grid grid-cols-2 gap-2">
                        {historyData!.currentStock.map(s => (
                          <div key={s.locationId} className="flex items-center justify-between rounded-lg bg-muted/30 px-3 py-2">
                            <div>
                              <p className="text-sm font-medium">{s.locationName}</p>
                              <p className="text-xs text-muted-foreground">{s.locationType}</p>
                            </div>
                            <div className="text-right">
                              <p className="text-sm font-bold">{s.qty} <span className="font-normal text-muted-foreground text-xs">{historyItem.baseUnit}</span></p>
                              {s.costPerUnit > 0 && <p className="text-xs text-muted-foreground">@ Rp {new Intl.NumberFormat('id-ID').format(s.costPerUnit)}</p>}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Lot Register */}
                  {(historyData?.lots?.length ?? 0) > 0 && (() => {
                    const method = (historyData!.valuationMethod ?? 'FIFO') as ValuationMethod
                    const stdCost = historyData!.standardCost ?? 0
                    const lotsAsValuation = historyData!.lots.map(l => ({
                      id: l.id, locationId: l.locationId, quantity: l.quantity,
                      costPerUnit: l.costPerUnit, createdAt: l.createdAt,
                      expiresAt: l.expiresAt, batch: l.batch,
                    }))
                    const sorted = sortByMethod(lotsAsValuation, method)
                    const lotInfoMap = new Map(historyData!.lots.map(l => [l.id, l]))
                    const totalQty = lotsAsValuation.reduce((s, l) => s + l.quantity, 0)
                    const totalValue = computeStockValue(lotsAsValuation, method, stdCost)
                    const methodDesc: Record<string, string> = {
                      FIFO: 'Oldest lot consumed first',
                      LIFO: 'Newest lot consumed first',
                      WEIGHTED_AVERAGE: 'All lots blended at average cost',
                      STANDARD: 'Fixed standard cost per unit',
                    }
                    return (
                      <div className="px-6 py-4 bg-slate-50/60">
                        <div className="flex items-center justify-between mb-3">
                          <div className="flex items-center gap-2">
                            <Layers className="h-3.5 w-3.5 text-muted-foreground" />
                            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Lot Register</p>
                          </div>
                          <div className="flex items-center gap-2">
                            <span className="text-[10px] px-2 py-0.5 rounded-full bg-blue-100 text-blue-700 font-semibold">{method.replace('_', ' ')}</span>
                            <span className="text-xs text-muted-foreground">{methodDesc[method]}</span>
                          </div>
                        </div>
                        <div className="rounded-lg border bg-white overflow-hidden">
                          <table className="w-full text-xs">
                            <thead className="bg-muted/40 text-muted-foreground">
                              <tr>
                                <th className="text-left px-3 py-2 font-medium">#</th>
                                <th className="text-left px-3 py-2 font-medium">Location</th>
                                <th className="text-left px-3 py-2 font-medium">Received</th>
                                <th className="text-left px-3 py-2 font-medium">Batch / Expiry</th>
                                <th className="text-right px-3 py-2 font-medium">Qty</th>
                                <th className="text-right px-3 py-2 font-medium">Cost / Unit</th>
                                <th className="text-right px-3 py-2 font-medium">Value</th>
                              </tr>
                            </thead>
                            <tbody className="divide-y">
                              {sorted.map((lot, i) => {
                                const effectiveCost = method === 'STANDARD' ? stdCost : method === 'WEIGHTED_AVERAGE'
                                  ? (totalQty > 0 ? lotsAsValuation.reduce((s, l) => s + l.quantity * l.costPerUnit, 0) / totalQty : 0)
                                  : lot.costPerUnit
                                const lotValue = lot.quantity * effectiveCost
                                const isExpired = lot.expiresAt ? new Date(lot.expiresAt) < new Date() : false
                                const isNearExpiry = lot.expiresAt && !isExpired
                                  ? (new Date(lot.expiresAt).getTime() - Date.now()) / 86400000 <= 30
                                  : false
                                return (
                                  <tr key={lot.id} className={i === 0 && (method === 'FIFO' || method === 'LIFO') ? 'bg-amber-50/50' : ''}>
                                    <td className="px-3 py-2 text-muted-foreground">
                                      {i === 0 && (method === 'FIFO' || method === 'LIFO')
                                        ? <span className="text-[10px] font-semibold text-[#bdac7e]">NEXT</span>
                                        : i + 1}
                                    </td>
                                    <td className="px-3 py-2 font-medium">{lotInfoMap.get(lot.id)?.locationName ?? '—'}</td>
                                    <td className="px-3 py-2 text-muted-foreground">
                                      {new Date(lot.createdAt).toLocaleDateString('id-ID', { day: '2-digit', month: 'short', year: '2-digit' })}
                                    </td>
                                    <td className="px-3 py-2">
                                      {lot.batch && <span className="font-mono text-[10px] bg-gray-100 px-1 rounded mr-1">{lot.batch}</span>}
                                      {lot.expiresAt && (
                                        <span className={`text-[10px] px-1.5 py-0.5 rounded-full font-medium ${isExpired ? 'bg-red-100 text-red-600' : isNearExpiry ? 'bg-orange-100 text-orange-600' : 'bg-green-50 text-green-600'}`}>
                                          {isExpired ? 'Expired' : new Date(lot.expiresAt).toLocaleDateString('id-ID', { day: '2-digit', month: 'short', year: '2-digit' })}
                                        </span>
                                      )}
                                      {!lot.batch && !lot.expiresAt && <span className="text-muted-foreground">—</span>}
                                    </td>
                                    <td className="px-3 py-2 text-right font-medium">{lot.quantity} <span className="text-muted-foreground font-normal">{historyItem?.baseUnit}</span></td>
                                    <td className="px-3 py-2 text-right text-muted-foreground">Rp {fmt(Math.round(effectiveCost))}</td>
                                    <td className="px-3 py-2 text-right font-medium">Rp {fmt(Math.round(lotValue))}</td>
                                  </tr>
                                )
                              })}
                            </tbody>
                            <tfoot className="bg-muted/30 border-t-2">
                              <tr>
                                <td colSpan={4} className="px-3 py-2 text-xs font-semibold text-muted-foreground">
                                  Total · {sorted.length} lot{sorted.length !== 1 ? 's' : ''}
                                </td>
                                <td className="px-3 py-2 text-right font-bold text-xs">{fmt(totalQty)} <span className="font-normal text-muted-foreground">{historyItem?.baseUnit}</span></td>
                                <td className="px-3 py-2 text-right text-xs text-muted-foreground">
                                  {method === 'WEIGHTED_AVERAGE' && totalQty > 0
                                    ? `WA: Rp ${fmt(Math.round(lotsAsValuation.reduce((s, l) => s + l.quantity * l.costPerUnit, 0) / totalQty))}`
                                    : method === 'STANDARD' ? `Std: Rp ${fmt(stdCost)}` : ''}
                                </td>
                                <td className="px-3 py-2 text-right font-bold text-xs">Rp {fmt(Math.round(totalValue))}</td>
                              </tr>
                            </tfoot>
                          </table>
                        </div>
                      </div>
                    )
                  })()}

                  {/* Timeline */}
                  <div className="px-6 py-4">
                    <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-4">Movement History</p>
                    {(historyData?.timeline?.length ?? 0) === 0 ? (
                      <div className="text-center py-8 text-muted-foreground">
                        <Package className="h-8 w-8 mx-auto mb-2 opacity-20" />
                        <p className="text-sm">No movement history yet</p>
                      </div>
                    ) : (
                      <div className="space-y-1">
                        {historyData!.timeline.map((entry, i) => (
                          <TimelineRow key={`${entry.id}-${i}`} entry={entry} />
                        ))}
                      </div>
                    )}
                  </div>
                </>
              )}
            </div>

            <div className="px-6 py-4 border-t bg-muted/20 shrink-0 text-right">
              <button onClick={() => setHistoryItem(null)} className="px-5 py-2 text-sm border rounded-lg hover:bg-muted transition-colors">
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

const TYPE_META: Record<string, { label: string; color: string; bg: string }> = {
  RECEIVE:    { label: 'Received',   color: 'text-green-700',  bg: 'bg-green-100'  },
  TRANSFER:   { label: 'Transfer',   color: 'text-blue-700',   bg: 'bg-blue-100'   },
  ADJUSTMENT: { label: 'Adjustment', color: 'text-amber-700',  bg: 'bg-amber-100'  },
  CONSUME:    { label: 'Consumed',   color: 'text-red-700',    bg: 'bg-red-100'    },
}

function TimelineRow({ entry }: { entry: HistoryEntry }) {
  const meta = TYPE_META[entry.type] ?? { label: entry.type, color: 'text-muted-foreground', bg: 'bg-muted' }
  const date = new Date(entry.date)
  const fmtD = date.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
  const fmtT = date.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })

  return (
    <div className="flex gap-3 py-2.5 group">
      <div className="flex flex-col items-center gap-1 shrink-0">
        <div className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold ${meta.bg} ${meta.color}`}>
          {entry.type === 'RECEIVE' ? '↓' : entry.type === 'TRANSFER' ? '→' : entry.type === 'CONSUME' ? '↑' : '±'}
        </div>
      </div>
      <div className="flex-1 min-w-0 pb-2.5 border-b group-last:border-0">
        <div className="flex items-start justify-between gap-2">
          <div className="min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <span className={`text-xs font-semibold px-1.5 py-0.5 rounded ${meta.bg} ${meta.color}`}>{meta.label}</span>
              {entry.supplier && <span className="text-xs text-muted-foreground">from <span className="font-medium text-foreground">{entry.supplier}</span></span>}
              {entry.poNumber && <span className="text-xs font-mono text-muted-foreground">{entry.poNumber}</span>}
              {entry.grNumber && <span className="text-xs font-mono text-muted-foreground">{entry.grNumber}</span>}
            </div>
            <div className="flex items-center gap-1.5 mt-1 text-xs text-muted-foreground flex-wrap">
              {entry.fromLocation && <><ArrowLeft className="h-3 w-3" /><span>{entry.fromLocation}</span></>}
              {entry.toLocation && <><ArrowRight className="h-3 w-3" /><span>{entry.toLocation}</span></>}
              {entry.by && <span>· {entry.by}</span>}
              {entry.notes && <span>· {entry.notes}</span>}
            </div>
          </div>
          <div className="text-right shrink-0">
            <p className={`text-sm font-bold ${meta.color}`}>
              {entry.type === 'CONSUME' || (entry.type === 'TRANSFER' && entry.fromLocation) ? '-' : '+'}{entry.qty} {entry.unit}
            </p>
            {entry.unitCost != null && entry.unitCost > 0 && (
              <p className="text-xs text-muted-foreground">@ Rp {new Intl.NumberFormat('id-ID').format(entry.unitCost)}</p>
            )}
            <p className="text-xs text-muted-foreground mt-0.5">{fmtD} {fmtT}</p>
          </div>
        </div>
      </div>
    </div>
  )
}
